# Generated by Django 5.1.5 on 2025-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weights', models.JSONField()),
                ('optimized_kpis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
